# Generated by Django 5.2.8 on 2025-11-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id_instrumento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('moneda', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'instrumento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id_mercado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'mercado',
                'managed': False,
            },
        ),
    ]
