# Generated by Django 5.2.8 on 2025-11-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('factor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'calificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calificaciontributaria',
            fields=[
                ('id_calificacion_tributaria', models.AutoField(primary_key=True, serialize=False)),
                ('secuencia_evento', models.CharField(blank=True, max_length=50, null=True)),
                ('evento_capital', models.CharField(blank=True, max_length=100, null=True)),
                ('anio', models.TextField(blank=True, null=True)),
                ('valor_historico', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ingreso_por_montos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calificaciontributaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factortributario',
            fields=[
                ('id_factor', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_factor', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion_factor', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'factortributario',
                'managed': False,
            },
        ),
    ]
