# Generated by Django 5.2.8 on 2025-11-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('fecha_carga', models.DateTimeField(blank=True, null=True)),
                ('estado_validacion', models.CharField(blank=True, max_length=9, null=True)),
                ('ruta', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'archivo',
                'managed': False,
            },
        ),
    ]
